
spring:
  mvc:
#    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: false
    contentnegotiation:
      favor-parameter: true
  resources:
    add-mappings: true
    cache:
      period: 11000