spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.ventoss.demo.* #监控SpringBean
      enable: true
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml
##  未使用mybatisplus时记住配置文件跟yaml配置只能二选一，不然直接炸裂
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true